# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='image',
            field=models.FileField(blank=True, upload_to='media/images/'),
        ),
    ]
