# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfind', '0002_auto_20181030_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
