# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-30 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfind', '0004_auto_20181030_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='loc_area',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pg',
            name='loc_street',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pg',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
