# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfind', '0005_auto_20181030_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
