# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgfind', '0006_auto_20181031_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=12.9716, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='pg',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=77.5946, max_digits=9, null=True),
        ),
    ]
